title: Kenny Lawrence Swamy
#logo: /assests/img/name.png
description: Masters in Data Science, Indiana University, May 2024
description: kennysawmy01@gmail.com
description: (812) 778-4957
#show_downloads: true
theme: jekyll-theme-minimal
